### PR TITLE
Custom event support

### PR DESCRIPTION
**Pull request by cmengler**

### CODE REVIEW

**Comment by CognitiveDisson** [comment]
Cool! Thanks for PR. Just add tests for pass the code coverage check. If you want you can also implement the cli support for this methods ( It is not necessary ).

**Comment by cmengler** [comment]
Thanks! I'll add tests and CLI support to this PR over the next few days. :)

**Comment by cmengler** [comment]
With the 8 issues reported by codeclimate, do I need to further action these @CognitiveDisson?

**Comment by CognitiveDisson** [comment]
No, all fine. Thanks for contributing!

**Comment by cmengler** [comment]
Thanks! I'll work on a PR for CLI support next :+1:

**Pull request merged**
